name: icons_launcher
description: A command-line tool that simplifies the task of updating your Flutter app's launcher icon.
maintainer: Mrr Hak
homepage: https://mrrhak.com
repository: https://github.com/mrrhak/icons_launcher
issue_tracker: https://github.com/mrrhak/icons_launcher/issues
version: 2.1.1
funding:
  - https://ko-fi.com/mrrhak
screenshots:
  - description: "Icons Launcher"
    path: assets/icons_launcher_profile.webp

dependencies:
  args: ^2.4.2
  image: ^4.0.17
  path: ^1.8.2
  universal_io: ^2.2.2
  yaml: ^3.1.2

environment:
  sdk: ">=2.17.0 <4.0.0"

dev_dependencies:
  build_runner: ^2.3.3
  build_version: ^2.1.1
  test: ^1.24.3
